### PR TITLE
OA: optimizations and few fixes

### PR DESCRIPTION
**Pull request by Rendevior**
+ fixed handling correct quality, for downloading.
+ fixed vimeo bug
+ Misc: speed meter

### CODE REVIEW

**Comment by Rendevior** [comment]
This is probably the bugless/stable version. Decided that will not rewrite it again.

**Comment by Rendevior** [comment]
Aight sure ball

**Review by fearocanity — APPROVED** [review]
Damn this looks good, stable than previous ver.

**Comment by fearocanity** [comment]
i guess this would be a stable release.
not to mention, Mp4upload was down yesterday, idk why. But scrapings still works though

**Comment by Rendevior** [comment]
> i guess this would be a stable release. not to mention, Mp4upload was down yesterday, idk why. But scrapings still works though

Lol, i don't personally use Mp4upload. like, i don't know... theres so many fast response providers out there xd.

**Pull request merged**
